### ISSUE TITLE
Add instructions for setup in Readme

### ISSUE THREAD

**Issue by schmug** [ppamidimarri/TeslaDashcamWeb#1]
Might it be possible to explain the setup procedure or is it basically setup the prerequisites and then copy those files?

**Comment by ppamidimarri** [comment]
@schmug I will complete the instructions soon.

**Comment by ppamidimarri** [comment]
@schmug I added all the instructions I can think of. The only piece of uncertainty is around the code for creating the drives in the teslausb project. I see that you have posted there, so you know that process. So please give these instructions and try and let me know if there are any issues. 

My problem is that I have built my drive with scripts I have saved to my personal Google Drive so I am guessing a little on where files will show up when downloaded using `git`.

**Comment by schmug** [comment]
@ppamidimarri Looks great I didn't mean to jump the gun so quickly on documentation but it looks great. [Readme changes](https://github.com/ppamidimarri/TeslaDashcamWeb/pull/2/commits/aa97055593c84439c50e552182e5078ada64f96d)

**Comment by ppamidimarri** [comment]
@schmug Thanks for that. With the directory structure created by git, the python scripts don't show up where the PHP files expect them, so added a step to move them.
